var Gres = {
  dactilografia : "Se deben ubicar los dedos índices en las teclas marcadas 'F' y 'J', de la línea del medio. En la posición adecuada, las manos no deben separarse del teclado y se utilizan todos los dedos. Control calla a Pequén y dicta la tecla. escape para salir. ",
  dIndice : "Se deben ubicar los dedos índices en las teclas marcadas 'F' y 'J', de la línea del medio. Con el dedo índice de la mano izquierda en la tecla 'F', ubicar sobre ella la tecla 'R' y debajo la tecla 'V', a la derecha la tecla 'G', sobre ella la tecla 'T' y debajo la tecla 'B' . Con el dedo indice de la mano derecha en la tecla 'J' ubicar sobre ella la tecla 'U' y debajo la tecla 'M', a la izquierda la tecla 'H', sobre ella la tecla 'Y' y debajo la tecla 'N' . ",
  dMedio : "Se deben ubicar los dedos índices en las teclas marcadas 'F' y 'J', de la línea del medio. el dedo medio de la mano izquierda se ubica sobre la tecla 'D', sobre ella se ubica la tecla 'E' y debajo la tecla 'C'. el dedo medio de la mano derecha se ubica sobre la tecla 'K', sobre ella se ubica la tecla 'I' y debajo la tecla 'Coma'. ",
  dAnular : "Se deben ubicar los dedos índices en las teclas marcadas 'F' y 'J', de la línea del medio. el dedo anular de la mano izquierda se ubica sobre la tecla 'S', sobre ella se ubica la tecla 'W' y debajo la tecla 'X'. el dedo anular de la mano derecha se ubica sobre la tecla 'L', sobre ella se ubica la tecla 'O' y debajo la tecla 'Punto'. ",
  dMeñique : "Se deben ubicar los dedos índices en las teclas marcadas 'F' y 'J', de la línea del medio. el dedo meñique de la mano izquierda se ubica sobre la tecla 'A', sobre ella se ubica la tecla 'Q' y debajo la tecla 'Z'. el dedo meñique de la mano derecha se ubica sobre la tecla 'Ñ', sobre ella se ubica la tecla 'P' y debajo la tecla 'Guión'. ",
  dAcentos : "el dedo meñique de la mano derecha se ubica sobre la tecla acento. de acuerdo a la configuracion del teclado se puede encontrar en la fila del medio, al lado de la letra 'ñ', o en la fila superior, al lado de la letra 'p', luego pulsar la vocal dictada. ",       
  palabras : "escribir la palabra dictada. al finalizar el dictado se obtendrá  el resultado del desempeño. pulsar barra espaciadora para escuchar la palabra dictada. para salir pulsar escape. ",
  letras : "escribir la letra dictada. al finalizar el dictado se obtendrá  el resultado del desempeño. pulsar barra espaciadora para escuchar la letra dictada. para salir pulsar escape. ",
PrEscribe : "Colocar el dedo índice izquierdo en la tecla marcada 'F' y el dedo índice derecho en la tecla marcada  'J'  del teclado QWERTY.  Estas teclas corresponden a los puntos braille uno y cuatro. Pulsar la tecla Barra Espaciadora para repetir el dictado. Al completar una práctica, el software informará el desempeño. Pulsar Escape para salir de la aplicación. ", 
PracticaAf : " escribir en estenografía la palabra dictada. utilizar el teclado Braille virtual. Colocar el dedo índice izquierdo en la tecla marcada 'F' y el dedo índice derecho en la tecla marcada  'J'  del teclado QWERTY que corresponden a los puntos braille uno y cuatro. Pulsar la Barra Espaciadora para repetir el dictado. Al completar una práctica, el software informará el desempeño. Pulsar Escape para salir de la actividad. ",
PracticaAfL : " Escribir el signo correspondiente a la letra dictada. utilizar el teclado Braille virtual. Colocar el dedo índice izquierdo en la tecla marcada 'F' y el dedo índice derecho en la tecla marcada  'J'  del teclado QWERTY.  Estas teclas corresponden a los puntos braille uno y cuatro. Pulsar la Barra Espaciadora para repetir el dictado. Al completar una práctica, el software informará el desempeño. Pulsar Escape para salir de la aplicación. ",
escribeE : "Escribir en estenografía la palabra: ",
BienEscribe : "¡Muy bien! Ahora escribir ",
noes : "no es correcto. Escribir ",
sinrealizar : "sin realizar",
realizadacon : "Realizada se registraron ",
realizadaCorr : "¡excelente práctica! realizada sin errores ",
error : " error",
errores : " errores",
escribesigno : "Escribir con el teclado virtual braille el signo ",
escribeElsigno : "Escribir el signo ",
noescorrecto : "No es correcto. Escribir ",
findelap : "Fin de la práctica con ",  
findelapCorr : "Fin de la práctica. ¡Excelente! No se registraron errores. ",
findelapUn : "Fin de la práctica. ¡Muy bien! se registró un error. ",
Psinrealizar : "Práctica sin realizar ",
PLrCorr : "realizada sin errores. ",
PLCErr : "Práctica de letras con ",
PLcUn : "¡Muy buena Práctica de letras! se registró un error ",
MenuPizarra : "Seleccionar una aplicación de pizarra braille ",
ecribirPizarraL : "escribir en la pizarra la letra ",
ecribirPizarraP : "escribir en la pizarra la palabra ",
escribir : "Escribir ",
noes : "No es ",
puntos : "puntos ",
punto : "punto ",
palabraD : "Palabra dictada ",
de : " de ",
escribiste : "escribiste. ",
escribir2: "escribir ",
ahoraesc : "reconocer los signos de: ",
NBtN : "no está bloqueado el teclado numérico ",
TnNh : "teclado numérico no habilitado. ",
TnH : "teclado numérico habilitado. ",
ListaPizarra : "seleccionar una práctica con las teclas de dirección  y luego pulsar enter. ",
PalabraPizarra : "Esta aplicación simula una pizarra braille utilizando 6 teclas del teclado numérico. Los signos braille que dicta el asistente Pequén se deben escribir como en la regleta o pizarra. La tecla marcada correspondiente al número 5 es la referencia para ubicar el punto braille 5. \
El signo generador se forma con los números 9, 6 y 3 que corresponden a los puntos 1, 2, 3 y los números 8, 5, 2 a los puntos 4, 5 y 6 respectivamente.  Pequén dicta una palabra, se debe escribir el signo que corresponde a cada letra pulsando los puntos en la pizarra braille virtual. Si el signo se escribe correctamente se puede escribir el siguiente o se escuchará qué puntos hay que pulsar, el error quedará registrado, a continuación se podrá escribir el siguiente signo hasta completar la palabra dictada. Para escuchar el reporte de la práctica pulsar barra espaciadora. ",
LetraPizarra : "Esta aplicación simula una pizarra braille utilizando 6 teclas del teclado numérico. Los signos braille que dicta el asistente Pequén se deben escribir como en la regleta o pizarra. La tecla marcada correspondiente al número 5 es la referencia para ubicar el punto braille 5. \
El signo generador se forma con los números 9, 6 y 3 que corresponden a los puntos 1, 2, 3 y los números 8, 5, 2 a los puntos 4, 5 y 6 respectivamente.  Escribir el signo que corresponde al la letra que Pequén dicta pulsando los puntos en la pizarra braille virtual. Si el signo se escribe correctamente Pequén dicta el siguiente o se escuchará qué puntos hay que pulsar. El error quedará registrado. Para volver a escuchar el signo dictado pulsar la barra espaciadora ",
PizarraPuntos : "En el teclado numérico usar los números 9, 6 y 3 que corresponden a los puntos 1, 2, 3. y los números 8, 5 y 2 que corresponden a los puntos 4, 5 y 6 respectivamente.",
nocorrespondePunto :"no corresponde el punto ",
PalabraTacto0: "Reconocer los signos braille que forman la palabra",
PalabraTacto : "Esta actividad se realiza con el teclado qwerty adaptado al tacto. Reconocer los signos braille que forman la palabra dictada y pulsar para verificar. si un signo es incorrecto se registra el error y se debe intentar nuevamente. ",
PrAlfa : " Escribe el alfabeto utilizando el teclado Braille virtual. Se debe colocar el dedo índice izquierdo en la tecla marcada 'F' y el dedo índice derecho en la tecla marcada  'J'  del teclado QWERTY.  Estas teclas corresponden a los puntos braille uno y cuatro. Pulsar la tecla Barra Espaciadora para repetir el dictado. Al completar una práctica, el software informa tu desempeño. Pulsar Escape para salir de la aplicación. ",
EscribeLetra : " Escribir con el teclado virtual braille la letra. ",
PrSignos :" Escribir los signos ortográficos utilizando el teclado Braille virtual.  Se debe colocar el dedo índice izquierdo en la tecla marcada 'F' y el dedo índice derecho en la tecla marcada  'J'  del teclado QWERTY.  Estas teclas corresponden a los puntos braille uno y cuatro. Pulsar la tecla Barra Espaciadora para repetir el dictado. Al completar una práctica, el software informa tu desempeño. Pulsar Escape para salir de la aplicación. ",
PrSignosM :" Escribir los signos Matemáticos. con teclado Braille virtual. Se debe colocar el dedo índice izquierdo en la tecla marcada 'F' y el dedo índice derecho en la tecla marcada  'J'  del teclado QWERTY.  Estas teclas corresponden a los puntos braille uno y cuatro. Pulsar la tecla Barra Espaciadora para repetir el dictado. Al completar una práctica, el software informa tu desempeño. Pulsar Escape para salir de la aplicación. ",
barraEscucharlos : "pulsar barra espaciadora para escucharlos. ",
barraEscuchalo : "pulsar barra espaciadora para escucharlo. ",
barraEscuchala : "pulsar barra espaciadora para escuchar las palabras. ",
PracticaMusica :"con el teclado virtual escribir los signos de música dictados. Al concluir se escuchará la melodía. Para imprimir en impresora braille pulsar F6. ",
barraEscuchala1 : "pulsar barra espaciadora para escucharla. ",
Abajo : "abajo ",
AbajoD : "abajo a la derecha ",
AbajoI : "abajo a la izquierda ",
Excelente : "Excelente. ",
MuyBueno : "Muy bueno. ",
Bueno : "Bueno. ",
Continua : "Continúa practicando. ",
TuDesempenio : "Tu desempeño fue ",
EnLaMisma : " en la misma fila",
MasArriba : " una fila más arriba",
MasAbajo : " una fila más abajo",
MasArriba2 : " dos filas más arriba",
MasAbajo2 : " dos filas más abajo",
Mderecha : " a la derecha ",
Mizquierda : " a la izquierda "

  }


