var SonidosA =
{
mosca : "la mosca, zumba",
burro : "el burro, rebuzna", 
lechuza : "la lechuza, chirea", 
caballo : "el caballo, relincha",
cabra : "la cabra, bala",
cerdo : "el cerdo, gruñe",
ciervo : "el ciervo, brama", 
cigüeña : "la cigueña, castañetea",
coyote : "el collote, aulla", 
urraca : "la urraca, grazna",
delfín : "el delfín, chasquea",
elefante : "el elefante, barrita",
foca : "la foca, gruñe",
gallina : "la gallina, cacarea",
gallo : "el gallo, canta",
gato : "el gato, maulla",
hipopótamo : "el hipopótamo, brama",
león : "el león, ruge",
tigre : "el tigre, ruge",
puma : "el puma, ruge",
koala : "el koala, brama",
lobo : "el lobo, aulla",
loro : "el loro, parlotea",
mono : "el mono, chilla",
oso : "el oso, gruñe",
oveja : "la oveja, bala",
ave : "el ave, trina",
pato : "el pato, grazna",
pingüino : "el pingüino, grazna",
perro : "el perro, ladra",
rana : "la rana, croa",
ratón : "el ratón, chilla", 
vaca : "la vaca, muge",
wapiti : "el wapiti, es un ciervo que brama",
sapo : "el sapo, croa"
}